// Code generated by entc, DO NOT EDIT.

package planet

import (
	"time"

	"github.com/facebookincubator/ent"
	"github.com/pdeguing/empire-and-foundation/ent/schema"
)

const (
	// Label holds the string label denoting the planet type in the database.
	Label = "planet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUUID holds the string denoting the uuid vertex property in the database.
	FieldUUID = "uuid"
	// FieldMetalStock holds the string denoting the metal_stock vertex property in the database.
	FieldMetalStock = "metal_stock"
	// FieldMetalMine holds the string denoting the metal_mine vertex property in the database.
	FieldMetalMine = "metal_mine"
	// FieldLastMetalUpdate holds the string denoting the last_metal_update vertex property in the database.
	FieldLastMetalUpdate = "last_metal_update"

	// Table holds the table name of the planet in the database.
	Table = "planets"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "planets"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
)

// Columns holds all SQL columns are planet fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUUID,
	FieldMetalStock,
	FieldMetalMine,
	FieldLastMetalUpdate,
}

var (
	mixin       = schema.Planet{}.Mixin()
	mixinFields = [...][]ent.Field{
		mixin[0].Fields(),
	}
	fields = schema.Planet{}.Fields()

	// descCreatedAt is the schema descriptor for created_at field.
	descCreatedAt = mixinFields[0][0].Descriptor()
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt = descCreatedAt.Default.(func() time.Time)

	// descUpdatedAt is the schema descriptor for updated_at field.
	descUpdatedAt = mixinFields[0][1].Descriptor()
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt = descUpdatedAt.Default.(func() time.Time)
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt = descUpdatedAt.UpdateDefault.(func() time.Time)

	// descMetalStock is the schema descriptor for metal_stock field.
	descMetalStock = fields[1].Descriptor()
	// MetalStockValidator is a validator for the "metal_stock" field. It is called by the builders before save.
	MetalStockValidator = descMetalStock.Validators[0].(func(int) error)

	// descMetalMine is the schema descriptor for metal_mine field.
	descMetalMine = fields[2].Descriptor()
	// MetalMineValidator is a validator for the "metal_mine" field. It is called by the builders before save.
	MetalMineValidator = descMetalMine.Validators[0].(func(int) error)
)
