// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"log"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"

	"github.com/pdeguing/empire-and-foundation/ent/planet"
)

// dsn for the database. In order to run the tests locally, run the following command:
//
//	 ENT_INTEGRATION_ENDPOINT="root:pass@tcp(localhost:3306)/test?parseTime=True" go test -v
//
var dsn string

func ExamplePlanet() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the planet's edges.

	// create planet vertex with its edges.
	pl := client.Planet.
		Create().
		SetCreatedAt(time.Now()).
		SetUpdatedAt(time.Now()).
		SetMetal(1).
		SetMetalLastUpdate(time.Now()).
		SetMetalRate(1).
		SetMetalProdLevel(1).
		SetMetalStorageLevel(1).
		SetHydrogen(1).
		SetHydrogenLastUpdate(time.Now()).
		SetHydrogenRate(1).
		SetHydrogenProdLevel(1).
		SetHydrogenStorageLevel(1).
		SetSilica(1).
		SetSilicaLastUpdate(time.Now()).
		SetSilicaRate(1).
		SetSilicaProdLevel(1).
		SetSilicaStorageLevel(1).
		SetPopulation(1).
		SetPopulationLastUpdate(time.Now()).
		SetPopulationRate(1).
		SetPopulationProdLevel(1).
		SetPopulationStorageLevel(1).
		SetEnergyCons(1).
		SetEnergyProd(1).
		SetSolarProdLevel(1).
		SetRegionCode(1).
		SetSystemCode(1).
		SetOrbitCode(1).
		SetSuborbitCode(1).
		SetPositionCode(1).
		SetName("string").
		SetPlanetType(planet.PlanetTypeHabitable).
		SetPlanetSkin("string").
		SaveX(ctx)
	log.Println("planet created:", pl)

	// query edges.

	// Output:
}
func ExampleSession() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the session's edges.

	// create session vertex with its edges.
	s := client.Session.
		Create().
		SetToken("string").
		SetData(nil).
		SetExpiry(time.Now()).
		SaveX(ctx)
	log.Println("session created:", s)

	// query edges.

	// Output:
}
func ExampleUser() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the user's edges.
	pl0 := client.Planet.
		Create().
		SetCreatedAt(time.Now()).
		SetUpdatedAt(time.Now()).
		SetMetal(1).
		SetMetalLastUpdate(time.Now()).
		SetMetalRate(1).
		SetMetalProdLevel(1).
		SetMetalStorageLevel(1).
		SetHydrogen(1).
		SetHydrogenLastUpdate(time.Now()).
		SetHydrogenRate(1).
		SetHydrogenProdLevel(1).
		SetHydrogenStorageLevel(1).
		SetSilica(1).
		SetSilicaLastUpdate(time.Now()).
		SetSilicaRate(1).
		SetSilicaProdLevel(1).
		SetSilicaStorageLevel(1).
		SetPopulation(1).
		SetPopulationLastUpdate(time.Now()).
		SetPopulationRate(1).
		SetPopulationProdLevel(1).
		SetPopulationStorageLevel(1).
		SetEnergyCons(1).
		SetEnergyProd(1).
		SetSolarProdLevel(1).
		SetRegionCode(1).
		SetSystemCode(1).
		SetOrbitCode(1).
		SetSuborbitCode(1).
		SetPositionCode(1).
		SetName("string").
		SetPlanetType(planet.PlanetTypeHabitable).
		SetPlanetSkin("string").
		SaveX(ctx)
	log.Println("planet created:", pl0)

	// create user vertex with its edges.
	u := client.User.
		Create().
		SetCreatedAt(time.Now()).
		SetUpdatedAt(time.Now()).
		SetUsername("string").
		SetEmail("string").
		SetPassword("string").
		AddPlanets(pl0).
		SaveX(ctx)
	log.Println("user created:", u)

	// query edges.
	pl0, err = u.QueryPlanets().First(ctx)
	if err != nil {
		log.Fatalf("failed querying planets: %v", err)
	}
	log.Println("planets found:", pl0)

	// Output:
}
