// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/pdeguing/empire-and-foundation/ent/planet"
	"github.com/pdeguing/empire-and-foundation/ent/schema"
	"github.com/pdeguing/empire-and-foundation/ent/user"

	"github.com/facebookincubator/ent"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	planetMixin := schema.Planet{}.Mixin()
	planetMixinFields := [...][]ent.Field{
		planetMixin[0].Fields(),
		planetMixin[1].Fields(),
		planetMixin[2].Fields(),
		planetMixin[3].Fields(),
		planetMixin[4].Fields(),
		planetMixin[5].Fields(),
		planetMixin[6].Fields(),
		planetMixin[7].Fields(),
		planetMixin[8].Fields(),
		planetMixin[9].Fields(),
	}
	planetFields := schema.Planet{}.Fields()
	_ = planetFields
	// planetDescCreatedAt is the schema descriptor for created_at field.
	planetDescCreatedAt := planetMixinFields[0][0].Descriptor()
	// planet.DefaultCreatedAt holds the default value on creation for the created_at field.
	planet.DefaultCreatedAt = planetDescCreatedAt.Default.(func() time.Time)
	// planetDescUpdatedAt is the schema descriptor for updated_at field.
	planetDescUpdatedAt := planetMixinFields[0][1].Descriptor()
	// planet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	planet.DefaultUpdatedAt = planetDescUpdatedAt.Default.(func() time.Time)
	// planet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	planet.UpdateDefaultUpdatedAt = planetDescUpdatedAt.UpdateDefault.(func() time.Time)
	// planetDescMetal is the schema descriptor for metal field.
	planetDescMetal := planetMixinFields[1][0].Descriptor()
	// planet.DefaultMetal holds the default value on creation for the metal field.
	planet.DefaultMetal = planetDescMetal.Default.(int64)
	// planet.MetalValidator is a validator for the "metal" field. It is called by the builders before save.
	planet.MetalValidator = planetDescMetal.Validators[0].(func(int64) error)
	// planetDescMetalProdLevel is the schema descriptor for metal_prod_level field.
	planetDescMetalProdLevel := planetMixinFields[1][1].Descriptor()
	// planet.DefaultMetalProdLevel holds the default value on creation for the metal_prod_level field.
	planet.DefaultMetalProdLevel = planetDescMetalProdLevel.Default.(int)
	// planet.MetalProdLevelValidator is a validator for the "metal_prod_level" field. It is called by the builders before save.
	planet.MetalProdLevelValidator = planetDescMetalProdLevel.Validators[0].(func(int) error)
	// planetDescMetalStorageLevel is the schema descriptor for metal_storage_level field.
	planetDescMetalStorageLevel := planetMixinFields[1][2].Descriptor()
	// planet.DefaultMetalStorageLevel holds the default value on creation for the metal_storage_level field.
	planet.DefaultMetalStorageLevel = planetDescMetalStorageLevel.Default.(int)
	// planet.MetalStorageLevelValidator is a validator for the "metal_storage_level" field. It is called by the builders before save.
	planet.MetalStorageLevelValidator = planetDescMetalStorageLevel.Validators[0].(func(int) error)
	// planetDescHydrogen is the schema descriptor for hydrogen field.
	planetDescHydrogen := planetMixinFields[2][0].Descriptor()
	// planet.DefaultHydrogen holds the default value on creation for the hydrogen field.
	planet.DefaultHydrogen = planetDescHydrogen.Default.(int64)
	// planet.HydrogenValidator is a validator for the "hydrogen" field. It is called by the builders before save.
	planet.HydrogenValidator = planetDescHydrogen.Validators[0].(func(int64) error)
	// planetDescHydrogenProdLevel is the schema descriptor for hydrogen_prod_level field.
	planetDescHydrogenProdLevel := planetMixinFields[2][1].Descriptor()
	// planet.DefaultHydrogenProdLevel holds the default value on creation for the hydrogen_prod_level field.
	planet.DefaultHydrogenProdLevel = planetDescHydrogenProdLevel.Default.(int)
	// planet.HydrogenProdLevelValidator is a validator for the "hydrogen_prod_level" field. It is called by the builders before save.
	planet.HydrogenProdLevelValidator = planetDescHydrogenProdLevel.Validators[0].(func(int) error)
	// planetDescHydrogenStorageLevel is the schema descriptor for hydrogen_storage_level field.
	planetDescHydrogenStorageLevel := planetMixinFields[2][2].Descriptor()
	// planet.DefaultHydrogenStorageLevel holds the default value on creation for the hydrogen_storage_level field.
	planet.DefaultHydrogenStorageLevel = planetDescHydrogenStorageLevel.Default.(int)
	// planet.HydrogenStorageLevelValidator is a validator for the "hydrogen_storage_level" field. It is called by the builders before save.
	planet.HydrogenStorageLevelValidator = planetDescHydrogenStorageLevel.Validators[0].(func(int) error)
	// planetDescSilica is the schema descriptor for silica field.
	planetDescSilica := planetMixinFields[3][0].Descriptor()
	// planet.DefaultSilica holds the default value on creation for the silica field.
	planet.DefaultSilica = planetDescSilica.Default.(int64)
	// planet.SilicaValidator is a validator for the "silica" field. It is called by the builders before save.
	planet.SilicaValidator = planetDescSilica.Validators[0].(func(int64) error)
	// planetDescSilicaProdLevel is the schema descriptor for silica_prod_level field.
	planetDescSilicaProdLevel := planetMixinFields[3][1].Descriptor()
	// planet.DefaultSilicaProdLevel holds the default value on creation for the silica_prod_level field.
	planet.DefaultSilicaProdLevel = planetDescSilicaProdLevel.Default.(int)
	// planet.SilicaProdLevelValidator is a validator for the "silica_prod_level" field. It is called by the builders before save.
	planet.SilicaProdLevelValidator = planetDescSilicaProdLevel.Validators[0].(func(int) error)
	// planetDescSilicaStorageLevel is the schema descriptor for silica_storage_level field.
	planetDescSilicaStorageLevel := planetMixinFields[3][2].Descriptor()
	// planet.DefaultSilicaStorageLevel holds the default value on creation for the silica_storage_level field.
	planet.DefaultSilicaStorageLevel = planetDescSilicaStorageLevel.Default.(int)
	// planet.SilicaStorageLevelValidator is a validator for the "silica_storage_level" field. It is called by the builders before save.
	planet.SilicaStorageLevelValidator = planetDescSilicaStorageLevel.Validators[0].(func(int) error)
	// planetDescPopulation is the schema descriptor for population field.
	planetDescPopulation := planetMixinFields[4][0].Descriptor()
	// planet.DefaultPopulation holds the default value on creation for the population field.
	planet.DefaultPopulation = planetDescPopulation.Default.(int64)
	// planet.PopulationValidator is a validator for the "population" field. It is called by the builders before save.
	planet.PopulationValidator = planetDescPopulation.Validators[0].(func(int64) error)
	// planetDescPopulationProdLevel is the schema descriptor for population_prod_level field.
	planetDescPopulationProdLevel := planetMixinFields[4][1].Descriptor()
	// planet.DefaultPopulationProdLevel holds the default value on creation for the population_prod_level field.
	planet.DefaultPopulationProdLevel = planetDescPopulationProdLevel.Default.(int)
	// planet.PopulationProdLevelValidator is a validator for the "population_prod_level" field. It is called by the builders before save.
	planet.PopulationProdLevelValidator = planetDescPopulationProdLevel.Validators[0].(func(int) error)
	// planetDescPopulationStorageLevel is the schema descriptor for population_storage_level field.
	planetDescPopulationStorageLevel := planetMixinFields[4][2].Descriptor()
	// planet.DefaultPopulationStorageLevel holds the default value on creation for the population_storage_level field.
	planet.DefaultPopulationStorageLevel = planetDescPopulationStorageLevel.Default.(int)
	// planet.PopulationStorageLevelValidator is a validator for the "population_storage_level" field. It is called by the builders before save.
	planet.PopulationStorageLevelValidator = planetDescPopulationStorageLevel.Validators[0].(func(int) error)
	// planetDescSolarProdLevel is the schema descriptor for solar_prod_level field.
	planetDescSolarProdLevel := planetMixinFields[5][0].Descriptor()
	// planet.DefaultSolarProdLevel holds the default value on creation for the solar_prod_level field.
	planet.DefaultSolarProdLevel = planetDescSolarProdLevel.Default.(int)
	// planet.SolarProdLevelValidator is a validator for the "solar_prod_level" field. It is called by the builders before save.
	planet.SolarProdLevelValidator = planetDescSolarProdLevel.Validators[0].(func(int) error)
	// planetDescShipFactoryLevel is the schema descriptor for ship_factory_level field.
	planetDescShipFactoryLevel := planetMixinFields[6][0].Descriptor()
	// planet.DefaultShipFactoryLevel holds the default value on creation for the ship_factory_level field.
	planet.DefaultShipFactoryLevel = planetDescShipFactoryLevel.Default.(int)
	// planet.ShipFactoryLevelValidator is a validator for the "ship_factory_level" field. It is called by the builders before save.
	planet.ShipFactoryLevelValidator = planetDescShipFactoryLevel.Validators[0].(func(int) error)
	// planetDescResearchCenterLevel is the schema descriptor for research_center_level field.
	planetDescResearchCenterLevel := planetMixinFields[7][0].Descriptor()
	// planet.DefaultResearchCenterLevel holds the default value on creation for the research_center_level field.
	planet.DefaultResearchCenterLevel = planetDescResearchCenterLevel.Default.(int)
	// planet.ResearchCenterLevelValidator is a validator for the "research_center_level" field. It is called by the builders before save.
	planet.ResearchCenterLevelValidator = planetDescResearchCenterLevel.Validators[0].(func(int) error)
	// planetDescRegionCode is the schema descriptor for region_code field.
	planetDescRegionCode := planetMixinFields[8][0].Descriptor()
	// planet.RegionCodeValidator is a validator for the "region_code" field. It is called by the builders before save.
	planet.RegionCodeValidator = planetDescRegionCode.Validators[0].(func(int) error)
	// planetDescSystemCode is the schema descriptor for system_code field.
	planetDescSystemCode := planetMixinFields[8][1].Descriptor()
	// planet.SystemCodeValidator is a validator for the "system_code" field. It is called by the builders before save.
	planet.SystemCodeValidator = planetDescSystemCode.Validators[0].(func(int) error)
	// planetDescOrbitCode is the schema descriptor for orbit_code field.
	planetDescOrbitCode := planetMixinFields[8][2].Descriptor()
	// planet.OrbitCodeValidator is a validator for the "orbit_code" field. It is called by the builders before save.
	planet.OrbitCodeValidator = planetDescOrbitCode.Validators[0].(func(int) error)
	// planetDescSuborbitCode is the schema descriptor for suborbit_code field.
	planetDescSuborbitCode := planetMixinFields[8][3].Descriptor()
	// planet.SuborbitCodeValidator is a validator for the "suborbit_code" field. It is called by the builders before save.
	planet.SuborbitCodeValidator = planetDescSuborbitCode.Validators[0].(func(int) error)
	// planetDescPositionCode is the schema descriptor for position_code field.
	planetDescPositionCode := planetMixinFields[8][4].Descriptor()
	// planet.PositionCodeValidator is a validator for the "position_code" field. It is called by the builders before save.
	planet.PositionCodeValidator = planetDescPositionCode.Validators[0].(func(int) error)
	// planetDescNumCaravel is the schema descriptor for num_caravel field.
	planetDescNumCaravel := planetMixinFields[9][0].Descriptor()
	// planet.DefaultNumCaravel holds the default value on creation for the num_caravel field.
	planet.DefaultNumCaravel = planetDescNumCaravel.Default.(int64)
	// planet.NumCaravelValidator is a validator for the "num_caravel" field. It is called by the builders before save.
	planet.NumCaravelValidator = planetDescNumCaravel.Validators[0].(func(int64) error)
	// planetDescNumLightFighter is the schema descriptor for num_light_fighter field.
	planetDescNumLightFighter := planetMixinFields[9][1].Descriptor()
	// planet.DefaultNumLightFighter holds the default value on creation for the num_light_fighter field.
	planet.DefaultNumLightFighter = planetDescNumLightFighter.Default.(int64)
	// planet.NumLightFighterValidator is a validator for the "num_light_fighter" field. It is called by the builders before save.
	planet.NumLightFighterValidator = planetDescNumLightFighter.Validators[0].(func(int64) error)
	// planetDescNumCorvette is the schema descriptor for num_corvette field.
	planetDescNumCorvette := planetMixinFields[9][2].Descriptor()
	// planet.DefaultNumCorvette holds the default value on creation for the num_corvette field.
	planet.DefaultNumCorvette = planetDescNumCorvette.Default.(int64)
	// planet.NumCorvetteValidator is a validator for the "num_corvette" field. It is called by the builders before save.
	planet.NumCorvetteValidator = planetDescNumCorvette.Validators[0].(func(int64) error)
	// planetDescNumFrigate is the schema descriptor for num_frigate field.
	planetDescNumFrigate := planetMixinFields[9][3].Descriptor()
	// planet.DefaultNumFrigate holds the default value on creation for the num_frigate field.
	planet.DefaultNumFrigate = planetDescNumFrigate.Default.(int64)
	// planet.NumFrigateValidator is a validator for the "num_frigate" field. It is called by the builders before save.
	planet.NumFrigateValidator = planetDescNumFrigate.Validators[0].(func(int64) error)
	// planetDescNumProbe is the schema descriptor for num_probe field.
	planetDescNumProbe := planetMixinFields[9][4].Descriptor()
	// planet.DefaultNumProbe holds the default value on creation for the num_probe field.
	planet.DefaultNumProbe = planetDescNumProbe.Default.(int64)
	// planet.NumProbeValidator is a validator for the "num_probe" field. It is called by the builders before save.
	planet.NumProbeValidator = planetDescNumProbe.Validators[0].(func(int64) error)
	// planetDescNumSmallCargo is the schema descriptor for num_small_cargo field.
	planetDescNumSmallCargo := planetMixinFields[9][5].Descriptor()
	// planet.DefaultNumSmallCargo holds the default value on creation for the num_small_cargo field.
	planet.DefaultNumSmallCargo = planetDescNumSmallCargo.Default.(int64)
	// planet.NumSmallCargoValidator is a validator for the "num_small_cargo" field. It is called by the builders before save.
	planet.NumSmallCargoValidator = planetDescNumSmallCargo.Validators[0].(func(int64) error)
	// planetDescNumMediumCargo is the schema descriptor for num_medium_cargo field.
	planetDescNumMediumCargo := planetMixinFields[9][6].Descriptor()
	// planet.DefaultNumMediumCargo holds the default value on creation for the num_medium_cargo field.
	planet.DefaultNumMediumCargo = planetDescNumMediumCargo.Default.(int64)
	// planet.NumMediumCargoValidator is a validator for the "num_medium_cargo" field. It is called by the builders before save.
	planet.NumMediumCargoValidator = planetDescNumMediumCargo.Validators[0].(func(int64) error)
	// planetDescNumColonizationArk is the schema descriptor for num_colonization_ark field.
	planetDescNumColonizationArk := planetMixinFields[9][7].Descriptor()
	// planet.DefaultNumColonizationArk holds the default value on creation for the num_colonization_ark field.
	planet.DefaultNumColonizationArk = planetDescNumColonizationArk.Default.(int64)
	// planet.NumColonizationArkValidator is a validator for the "num_colonization_ark" field. It is called by the builders before save.
	planet.NumColonizationArkValidator = planetDescNumColonizationArk.Validators[0].(func(int64) error)
	// planetDescName is the schema descriptor for name field.
	planetDescName := planetFields[0].Descriptor()
	// planet.DefaultName holds the default value on creation for the name field.
	planet.DefaultName = planetDescName.Default.(string)
	// planetDescLastResourceUpdate is the schema descriptor for last_resource_update field.
	planetDescLastResourceUpdate := planetFields[3].Descriptor()
	// planet.DefaultLastResourceUpdate holds the default value on creation for the last_resource_update field.
	planet.DefaultLastResourceUpdate = planetDescLastResourceUpdate.Default.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields := [...][]ent.Field{
		userMixin[0].Fields(),
	}
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields[0][0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields[0][1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
