// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/pdeguing/empire-and-foundation/ent/planet"
	"github.com/pdeguing/empire-and-foundation/ent/predicate"
	"github.com/pdeguing/empire-and-foundation/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config

	updated_at     *time.Time
	username       *string
	email          *string
	password       *string
	planets        map[int]struct{}
	removedPlanets map[int]struct{}
	predicates     []predicate.User
}

// Where adds a new predicate for the builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.predicates = append(uu.predicates, ps...)
	return uu
}

// SetUpdatedAt sets the updated_at field.
func (uu *UserUpdate) SetUpdatedAt(t time.Time) *UserUpdate {
	uu.updated_at = &t
	return uu
}

// SetUsername sets the username field.
func (uu *UserUpdate) SetUsername(s string) *UserUpdate {
	uu.username = &s
	return uu
}

// SetEmail sets the email field.
func (uu *UserUpdate) SetEmail(s string) *UserUpdate {
	uu.email = &s
	return uu
}

// SetPassword sets the password field.
func (uu *UserUpdate) SetPassword(s string) *UserUpdate {
	uu.password = &s
	return uu
}

// AddPlanetIDs adds the planets edge to Planet by ids.
func (uu *UserUpdate) AddPlanetIDs(ids ...int) *UserUpdate {
	if uu.planets == nil {
		uu.planets = make(map[int]struct{})
	}
	for i := range ids {
		uu.planets[ids[i]] = struct{}{}
	}
	return uu
}

// AddPlanets adds the planets edges to Planet.
func (uu *UserUpdate) AddPlanets(p ...*Planet) *UserUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uu.AddPlanetIDs(ids...)
}

// RemovePlanetIDs removes the planets edge to Planet by ids.
func (uu *UserUpdate) RemovePlanetIDs(ids ...int) *UserUpdate {
	if uu.removedPlanets == nil {
		uu.removedPlanets = make(map[int]struct{})
	}
	for i := range ids {
		uu.removedPlanets[ids[i]] = struct{}{}
	}
	return uu
}

// RemovePlanets removes planets edges to Planet.
func (uu *UserUpdate) RemovePlanets(p ...*Planet) *UserUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uu.RemovePlanetIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	if uu.updated_at == nil {
		v := user.UpdateDefaultUpdatedAt()
		uu.updated_at = &v
	}
	return uu.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	var (
		builder  = sql.Dialect(uu.driver.Dialect())
		selector = builder.Select(user.FieldID).From(builder.Table(user.Table))
	)
	for _, p := range uu.predicates {
		p(selector)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err = uu.driver.Query(ctx, query, args, rows); err != nil {
		return 0, err
	}
	defer rows.Close()

	var ids []int
	for rows.Next() {
		var id int
		if err := rows.Scan(&id); err != nil {
			return 0, fmt.Errorf("ent: failed reading id: %v", err)
		}
		ids = append(ids, id)
	}
	if len(ids) == 0 {
		return 0, nil
	}

	tx, err := uu.driver.Tx(ctx)
	if err != nil {
		return 0, err
	}
	var (
		res     sql.Result
		updater = builder.Update(user.Table)
	)
	updater = updater.Where(sql.InInts(user.FieldID, ids...))
	if value := uu.updated_at; value != nil {
		updater.Set(user.FieldUpdatedAt, *value)
	}
	if value := uu.username; value != nil {
		updater.Set(user.FieldUsername, *value)
	}
	if value := uu.email; value != nil {
		updater.Set(user.FieldEmail, *value)
	}
	if value := uu.password; value != nil {
		updater.Set(user.FieldPassword, *value)
	}
	if !updater.Empty() {
		query, args := updater.Query()
		if err := tx.Exec(ctx, query, args, &res); err != nil {
			return 0, rollback(tx, err)
		}
	}
	if len(uu.removedPlanets) > 0 {
		eids := make([]int, len(uu.removedPlanets))
		for eid := range uu.removedPlanets {
			eids = append(eids, eid)
		}
		query, args := builder.Update(user.PlanetsTable).
			SetNull(user.PlanetsColumn).
			Where(sql.InInts(user.PlanetsColumn, ids...)).
			Where(sql.InInts(planet.FieldID, eids...)).
			Query()
		if err := tx.Exec(ctx, query, args, &res); err != nil {
			return 0, rollback(tx, err)
		}
	}
	if len(uu.planets) > 0 {
		for _, id := range ids {
			p := sql.P()
			for eid := range uu.planets {
				p.Or().EQ(planet.FieldID, eid)
			}
			query, args := builder.Update(user.PlanetsTable).
				Set(user.PlanetsColumn, id).
				Where(sql.And(p, sql.IsNull(user.PlanetsColumn))).
				Query()
			if err := tx.Exec(ctx, query, args, &res); err != nil {
				return 0, rollback(tx, err)
			}
			affected, err := res.RowsAffected()
			if err != nil {
				return 0, rollback(tx, err)
			}
			if int(affected) < len(uu.planets) {
				return 0, rollback(tx, &ConstraintError{msg: fmt.Sprintf("one of \"planets\" %v already connected to a different \"User\"", keys(uu.planets))})
			}
		}
	}
	if err = tx.Commit(); err != nil {
		return 0, err
	}
	return len(ids), nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	id int

	updated_at     *time.Time
	username       *string
	email          *string
	password       *string
	planets        map[int]struct{}
	removedPlanets map[int]struct{}
}

// SetUpdatedAt sets the updated_at field.
func (uuo *UserUpdateOne) SetUpdatedAt(t time.Time) *UserUpdateOne {
	uuo.updated_at = &t
	return uuo
}

// SetUsername sets the username field.
func (uuo *UserUpdateOne) SetUsername(s string) *UserUpdateOne {
	uuo.username = &s
	return uuo
}

// SetEmail sets the email field.
func (uuo *UserUpdateOne) SetEmail(s string) *UserUpdateOne {
	uuo.email = &s
	return uuo
}

// SetPassword sets the password field.
func (uuo *UserUpdateOne) SetPassword(s string) *UserUpdateOne {
	uuo.password = &s
	return uuo
}

// AddPlanetIDs adds the planets edge to Planet by ids.
func (uuo *UserUpdateOne) AddPlanetIDs(ids ...int) *UserUpdateOne {
	if uuo.planets == nil {
		uuo.planets = make(map[int]struct{})
	}
	for i := range ids {
		uuo.planets[ids[i]] = struct{}{}
	}
	return uuo
}

// AddPlanets adds the planets edges to Planet.
func (uuo *UserUpdateOne) AddPlanets(p ...*Planet) *UserUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uuo.AddPlanetIDs(ids...)
}

// RemovePlanetIDs removes the planets edge to Planet by ids.
func (uuo *UserUpdateOne) RemovePlanetIDs(ids ...int) *UserUpdateOne {
	if uuo.removedPlanets == nil {
		uuo.removedPlanets = make(map[int]struct{})
	}
	for i := range ids {
		uuo.removedPlanets[ids[i]] = struct{}{}
	}
	return uuo
}

// RemovePlanets removes planets edges to Planet.
func (uuo *UserUpdateOne) RemovePlanets(p ...*Planet) *UserUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uuo.RemovePlanetIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	if uuo.updated_at == nil {
		v := user.UpdateDefaultUpdatedAt()
		uuo.updated_at = &v
	}
	return uuo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	u, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return u
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (u *User, err error) {
	var (
		builder  = sql.Dialect(uuo.driver.Dialect())
		selector = builder.Select(user.Columns...).From(builder.Table(user.Table))
	)
	user.ID(uuo.id)(selector)
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err = uuo.driver.Query(ctx, query, args, rows); err != nil {
		return nil, err
	}
	defer rows.Close()

	var ids []int
	for rows.Next() {
		var id int
		u = &User{config: uuo.config}
		if err := u.FromRows(rows); err != nil {
			return nil, fmt.Errorf("ent: failed scanning row into User: %v", err)
		}
		id = u.ID
		ids = append(ids, id)
	}
	switch n := len(ids); {
	case n == 0:
		return nil, &ErrNotFound{fmt.Sprintf("User with id: %v", uuo.id)}
	case n > 1:
		return nil, fmt.Errorf("ent: more than one User with the same id: %v", uuo.id)
	}

	tx, err := uuo.driver.Tx(ctx)
	if err != nil {
		return nil, err
	}
	var (
		res     sql.Result
		updater = builder.Update(user.Table)
	)
	updater = updater.Where(sql.InInts(user.FieldID, ids...))
	if value := uuo.updated_at; value != nil {
		updater.Set(user.FieldUpdatedAt, *value)
		u.UpdatedAt = *value
	}
	if value := uuo.username; value != nil {
		updater.Set(user.FieldUsername, *value)
		u.Username = *value
	}
	if value := uuo.email; value != nil {
		updater.Set(user.FieldEmail, *value)
		u.Email = *value
	}
	if value := uuo.password; value != nil {
		updater.Set(user.FieldPassword, *value)
		u.Password = *value
	}
	if !updater.Empty() {
		query, args := updater.Query()
		if err := tx.Exec(ctx, query, args, &res); err != nil {
			return nil, rollback(tx, err)
		}
	}
	if len(uuo.removedPlanets) > 0 {
		eids := make([]int, len(uuo.removedPlanets))
		for eid := range uuo.removedPlanets {
			eids = append(eids, eid)
		}
		query, args := builder.Update(user.PlanetsTable).
			SetNull(user.PlanetsColumn).
			Where(sql.InInts(user.PlanetsColumn, ids...)).
			Where(sql.InInts(planet.FieldID, eids...)).
			Query()
		if err := tx.Exec(ctx, query, args, &res); err != nil {
			return nil, rollback(tx, err)
		}
	}
	if len(uuo.planets) > 0 {
		for _, id := range ids {
			p := sql.P()
			for eid := range uuo.planets {
				p.Or().EQ(planet.FieldID, eid)
			}
			query, args := builder.Update(user.PlanetsTable).
				Set(user.PlanetsColumn, id).
				Where(sql.And(p, sql.IsNull(user.PlanetsColumn))).
				Query()
			if err := tx.Exec(ctx, query, args, &res); err != nil {
				return nil, rollback(tx, err)
			}
			affected, err := res.RowsAffected()
			if err != nil {
				return nil, rollback(tx, err)
			}
			if int(affected) < len(uuo.planets) {
				return nil, rollback(tx, &ConstraintError{msg: fmt.Sprintf("one of \"planets\" %v already connected to a different \"User\"", keys(uuo.planets))})
			}
		}
	}
	if err = tx.Commit(); err != nil {
		return nil, err
	}
	return u, nil
}
